##自定义错误枚举

```rust
use std::fs::File;
use std::io::{self, Read};
use thiserror::Error;

#[derive(Error, Debug)]
enum FileReadError {
    #[error("Failed to open file: {0}")]
    OpenError(#[from] io::Error),
    #[error("Failed to read file content: {0}")]
    ReadError(#[from] io::Error),
}

fn read_file() -> Result<String, FileReadError> {
    let mut file = File::open("example.txt").map_err(FileReadError::OpenError)?;
    let mut content = String::new();
    file.read_to_string(&mut content).map_err(FileReadError::ReadError)?;
    Ok(content)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    match read_file() {
        Ok(content) => println!("File content: {}", content),
        Err(e) => match e {
            FileReadError::OpenError(err) => eprintln!("Error opening file: {}", err),
            FileReadError::ReadError(err) => eprintln!("Error reading file content: {}", err),
        },
    }
    Ok(())
}
```
##不处理错误，遇到错误就传播
```rust
use std::fs::File;
use std::io::{self, Read};

fn read_file() -> io::Result<String> {
    let mut file = File::open("example.txt")?;
    let mut content = String::new();
    file.read_to_string(&mut content)?;
    Ok(content)
}

fn main() -> io::Result<()> {
    let content = read_file()?;
    println!("File content: {}", content);
    Ok(())
}
```



